### ISSUE TITLE
This method can cause UI unresponsiveness if invoked on the main thread. Instead, consider waiting for the -locationManagerDidChangeAuthorization: callback and checking authorizationStatus first.

### ISSUE THREAD

**Issue by harryngict** [tritondigital/ios-sdk#12]
Hi Triton team,

We are getting the issue:
(This method can cause UI unresponsiveness if invoked on the main thread. Instead, consider waiting for the `-locationManagerDidChangeAuthorization:` callback and checking `authorizationStatus` first.) 

 when we execute:  `TritonPlayer(delegate: self, andSettings: settings)`

Please help verify and fix.

**Comment by harryngict** [comment]
cc: @klandman klandman Kallie

**Comment by jd-buys** [comment]
@harryngict We have fixed the issue in the latest release.
