### ISSUE TITLE
Example project and framework broken in releases > 2.6.5

### ISSUE THREAD

**Issue by hellotoby** [tritondigital/ios-sdk#5]
The example project and framework are broken in the following releases:

- 2.6.6
- 2.6.7
- 2.6.8

The following build error is returned when attempting to use the TritonPlayerSDK.framework or the example project in both releases.

```
ld: framework not found TritonPlayerSDK
```

**Comment by jd-buys** [comment]
Thanks for bringing it to our attention.
I tested 2.6.6 and that worked, but I did update the following versions where the SDK did not build correctly:
- 2.6.7
- 2.6.8
